export interface MinecraftEntity {
  key: string;
  type: string;
  meta: number;
  name: string;
  image: string;
}

export const MINECRAFT_ENTITITES = {
  'item': {'type': 1, 'name': 'Dropped Item'},
  'xp_orb': {'type': 2, 'name': 'Experience Orb'},
  'area_effect_cloud': {'type': 3, 'name': 'Area Effect Cloud'},
  'elder_guardian': {'type': 4, 'name': 'Elder Guardian'},
  'wither_skeleton': {'type': 5, 'name': 'Wither Skeleton'},
  'stray': {'type': 6, 'name': 'Stray'},
  'egg': {'type': 7, 'name': 'Egg'},
  'leash_knot': {'type': 8, 'name': 'Lead Knot'},
  'painting': {'type': 9, 'name': 'Painting'},
  'arrow': {'type': 10, 'name': 'Arrow'},
  'snowball': {'type': 11, 'name': 'Snowball'},
  'fireball': {'type': 12, 'name': 'Ghast Fireball'},
  'small_fireball': {'type': 13, 'name': 'Blaze Fireball'},
  'ender_pearl': {'type': 14, 'name': 'Ender Pearl'},
  'eye_of_ender_signal': {'type': 15, 'name': 'Eye of Ender'},
  'potion': {'type': 16, 'name': 'Splash Potion'},
  'xp_bottle': {'type': 17, 'name': 'Bottle o\' Enchanting'},
  'item_frame': {'type': 18, 'name': 'Item Frame'},
  'wither_skull': {'type': 19, 'name': 'Wither Skull'},
  'tnt': {'type': 20, 'name': 'Primed TNT'},
  'falling_block': {'type': 21, 'name': 'Falling Block'},
  'fireworks_rocket': {'type': 22, 'name': 'Firework Rocket'},
  'husk': {'type': 23, 'name': 'Husk'},
  'spectral_arrow': {'type': 24, 'name': 'Spectral Arrow'},
  'shulker_bullet': {'type': 25, 'name': 'Shulker Bullet'},
  'dragon_fireball': {'type': 26, 'name': 'Dragon Fireball'},
  'zombie_villager': {'type': 27, 'name': 'Zombie Villager'},
  'skeleton_horse': {'type': 28, 'name': 'Skeleton Horse'},
  'zombie_horse': {'type': 29, 'name': 'Zombie Horse'},
  'armor_stand': {'type': 30, 'name': 'Armor Stand'},
  'donkey': {'type': 31, 'name': 'Donkey'},
  'mule': {'type': 32, 'name': 'Mule'},
  'evocation_fangs': {'type': 33, 'name': 'Evocation Fangs'},
  'evocation_illager': {'type': 34, 'name': 'Evoker'},
  'vex': {'type': 35, 'name': 'Vex'},
  'vindication_illager': {'type': 36, 'name': 'Vindicator'},
  'illusion_illager': {'type': 37, 'name': 'Illusioner'},
  'commandblock_minecart': {'type': 40, 'name': 'Minecart with Command Block'},
  'boat': {'type': 41, 'name': 'Boat'},
  'minecart': {'type': 42, 'name': 'Minecart'},
  'chest_minecart': {'type': 43, 'name': 'Storage Minecart'},
  'furnace_minecart': {'type': 44, 'name': 'Powered Minecart'},
  'tnt_minecart': {'type': 45, 'name': 'Minecart with TNT'},
  'hopper_minecart': {'type': 46, 'name': 'Minecart with Hopper'},
  'spawner_minecart': {'type': 47, 'name': 'Minecart with Spawner'},
  'creeper': {'type': 50, 'name': 'Creeper'},
  'skeleton': {'type': 51, 'name': 'Skeleton'},
  'spider': {'type': 52, 'name': 'Spider'},
  'giant': {'type': 53, 'name': 'Giant Zombie'},
  'zombie': {'type': 54, 'name': 'Zombie'},
  'slime': {'type': 55, 'name': 'Slime'},
  'ghast': {'type': 56, 'name': 'Ghast'},
  'zombie_pigman': {'type': 57, 'name': 'Zombie Pigman'},
  'enderman': {'type': 58, 'name': 'Enderman'},
  'cave_spider': {'type': 59, 'name': 'Cave Spider'},
  'silverfish': {'type': 60, 'name': 'Silverfish'},
  'blaze': {'type': 61, 'name': 'Blaze'},
  'magma_cube': {'type': 62, 'name': 'Magma Cube'},
  'ender_dragon': {'type': 63, 'name': 'Ender Dragon'},
  'wither': {'type': 64, 'name': 'Wither'},
  'bat': {'type': 65, 'name': 'Bat'},
  'witch': {'type': 66, 'name': 'Witch'},
  'endermite': {'type': 67, 'name': 'Endermite'},
  'guardian': {'type': 68, 'name': 'Guardian'},
  'shulker': {'type': 69, 'name': 'Shulker'},
  'pig': {'type': 90, 'name': 'Pig'},
  'sheep': {'type': 91, 'name': 'Sheep'},
  'cow': {'type': 92, 'name': 'Cow'},
  'chicken': {'type': 93, 'name': 'Chicken'},
  'squid': {'type': 94, 'name': 'Squid'},
  'wolf': {'type': 95, 'name': 'Wolf'},
  'mooshroom': {'type': 96, 'name': 'Mooshroom'},
  'snowman': {'type': 97, 'name': 'Snow Golem'},
  'ocelot': {'type': 98, 'name': 'Ocelot'},
  'villager_golem': {'type': 99, 'name': 'Iron Golem'},
  'horse': {'type': 100, 'name': 'Horse'},
  'rabiit': {'type': 101, 'name': 'Rabbit'},
  'polar_bear': {'type': 102, 'name': 'Polar Bear'},
  'llama': {'type': 103, 'name': 'Llama'},
  'llama_spit': {'type': 104, 'name': 'Llama Spit'},
  'parrot': {'type': 105, 'name': 'Parrot'},
  'villager': {'type': 120, 'name': 'Villager'},
  'ender_crystal': {'type': 200, 'name': 'Ender Crystal'}
};
